services:
  discovery:
    container_name: discovery
    image: servicediscovery
    ports:
      - "8000:8000"
    restart: always
    networks:
      - alumni
    environment:
      - PORT=8000
      - EUREKA_URI=http://discovery:8000/eureka

  config:
    container_name: config
    image: configserver
    ports:
      - "8001:8001"
    restart: always
    depends_on:
      - discovery
    networks:
      - alumni
    environment:
      - PORT=8001
      - EUREKA_URI=http://discovery:8000/eureka
      - EVENT_PORT=8801
      - EVENT_DB_URL=eventsdb:3306
      - EVENT_DB_NAME=eventsDb
      - EVENT_DB_USER=root
      - EVENT_DB_PASSWORD=1

  apigateway:
    container_name: apigateway
    image: apigateway
    ports:
      - "8002:8002"
    restart: always
    depends_on:
      - discovery
      - config
    networks:
      - alumni
    environment:
      - PORT=8002
      - EUREKA_URI=http://discovery:8000/eureka

  eventservice:
    container_name: eventservice
    image: eventservice
    ports:
      - "8801:8801"
    restart: always
    depends_on:
      - discovery
      - config
      - apigateway
      - eventsdb
      - userservice
    networks:
      - alumni
      - events
    environment:
      - PORT=8801
      - EUREKA_URI=http://discovery:8000/eureka
      - CONFIG_URI=http://config:8001
      - EVENT_DB_URL=eventsdb:3306
      - EVENT_DB_NAME=eventsdb
      - EVENT_DB_USER=root
      - EVENT_DB_PASSWORD=1

  chatservice:
    container_name: chatservice
    image: chatservice
    ports:
      - "8809:8809"
    restart: always
    depends_on:
      - discovery
      - config
      - apigateway
      - chatdb
      - userservice
    networks:
      - alumni
      - chat
    environment:
      - PORT=8809
      - EUREKA_URI=http://discovery:8000/eureka
      - CONFIG_URI=http://config:8001
      - CHAT_DB_URL=chatdb:3306
      - CHAT_DB_NAME=chatDB
      - CHAT_DB_USER=root
      - CHAT_DB_PASSWORD=1

  userservice:
    container_name: userservice
    image: userservice
    ports:
      - "8802:8802"
    restart: always
    depends_on:
      - discovery
      - config
      - apigateway
      - usersdb
      - rabbitmq
      - zipkin
    networks:
      - alumni
      - users
    environment:
      - PORT=8802
      - EUREKA_URI=http://discovery:8000/eureka
      - CONFIG_URI=http://config:8001
      - USER_DB_URL=usersdb:3306
      - USER_DB_NAME=usersdb
      - USER_DB_USER=root
      - USER_DB_PASSWORD=1

  courseservice:
    container_name: courseservice
    image: courseservice
    ports:
      - "8808:8808"
    restart: always
    depends_on:
      - discovery
      - config
      - apigateway
      - coursesdb
      - rabbitmq
      - zipkin
    networks:
      - alumni
      - courses
    environment:
      - PORT=8808
      - EUREKA_URI=http://discovery:8000/eureka
      - CONFIG_URI=http://config:8001
      - USER_DB_URL=coursesdb:3306
      - USER_DB_NAME=coursesdb
      - USER_DB_USER=root
      - USER_DB_PASSWORD=1

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672"

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  eventsdb:
    container_name: eventsdb
    image: mysql
    ports:
      - "9901:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1
    restart: always
    networks:
      - events

  usersdb:
    container_name: usersdb
    image: mysql
    ports:
      - "9902:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1
    restart: always
    networks:
      - users

  coursesdb:
    container_name: coursesdb
    image: mysql
    ports:
      - "9920:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1
    restart: always
    networks:
      - courses

  chatdb:
    container_name: chatdb
    image: mysql
    ports:
      - "9909:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1
    restart: always
    networks:
      - chat

networks:
  alumni:
    driver: bridge
  events:
    driver: bridge
  users:
    driver: bridge
  courses:
    driver: bridge
  chat:
    driver: bridge