services:
  discovery:
    container_name: discovery
    image: servicediscovery
    ports:
      - "8000:8000"
    restart: always
    networks:
      - alumni
    environment:
      - PORT=8000
      - EUREKA_URI=http://discovery:8000/eureka

  config:
    container_name: config
    image: configserver
    ports:
      - "8001:8001"
    restart: always
    depends_on:
      - discovery
    networks:
      - alumni
    environment:
      - PORT=8001
      - EUREKA_URI=http://discovery:8000/eureka
      - EVENT_PORT=8801
      - EVENT_DB_URL=eventsdb:3306
      - EVENT_DB_NAME=eventsDb
      - EVENT_DB_USER=root
      - EVENT_DB_PASSWORD=1
      - JOB_PORT=8803
      - JOB_DB_URL=eventsdb:3306
      - JOB_DB_NAME=eventsDb
      - JOB_DB_USER=root
      - JOB_DB_PASSWORD=1

  apigateway:
    container_name: apigateway
    image: apigateway
    ports:
      - "8002:8002"
    restart: always
    depends_on:
      - discovery
      - config
    networks:
      - alumni
    environment:
      - PORT=8002
      - EUREKA_URI=http://discovery:8000/eureka

  eventservice:
    container_name: eventservice
    image: eventservice
    ports:
      - "8801:8801"
    restart: always
    depends_on:
      - discovery
      - config
      - apigateway
      - eventsdb
      - userservice
    networks:
      - alumni
      - events
    environment:
      - PORT=8801
      - EUREKA_URI=http://discovery:8000/eureka
      - CONFIG_URI=http://config:8001
      - EVENT_DB_URL=eventsdb:3306
      - EVENT_DB_NAME=eventsdb
      - EVENT_DB_USER=root
      - EVENT_DB_PASSWORD=1

  jobservice:
    container_name: jobservice
    image: jobservice
    ports:
      - "8803:8803"
    restart: always
    depends_on:
      - discovery
      - config
      - apigateway
      - userservice
      - jobsdb
    networks:
      - alumni
      - jobs
    environment:
      - PORT=8803
      - EUREKA_URI=http://discovery:8000/eureka
      - CONFIG_URI=http://config:8001
      - JOB_DB_URL=jobsdb:3306
      - JOB_DB_NAME=jobsdb
      - JOB_DB_USER=root
      - JOB_DB_PASSWORD=1

  chatservice:
    container_name: chatservice
    image: chatservice
    ports:
      - "8809:8809"
    restart: always
    depends_on:
      - discovery
      - config
      - apigateway
      - userservice
      - jobsdb
      - chatdb
    networks:
      - alumni
      - chat
    environment:
      - PORT=8809
      - EUREKA_URI=http://discovery:8000/eureka
      - CONFIG_URI=http://config:8001
      - CHAT_DB_URL=chatdb:3306
      - CHAT_DB_NAME=chatDB
      - CHAT_DB_USER=root
      - CHAT_DB_PASSWORD=1

  userservice:
    container_name: userservice
    image: userservice
    ports:
      - "8802:8802"
    restart: always
    depends_on:
      - discovery
      - config
      - apigateway
      - usersdb
    networks:
      - alumni
      - users
    environment:
      - PORT=8802
      - EUREKA_URI=http://discovery:8000/eureka
      - CONFIG_URI=http://config:8001
      - USER_DB_URL=usersdb:3306
      - USER_DB_NAME=usersdb
      - USER_DB_USER=root
      - USER_DB_PASSWORD=1

  eventsdb:
    container_name: eventsdb
    image: mysql
    ports:
      - "9901:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1
    restart: always
    networks:
      - events
  jobsdb:
    container_name: jobsdb
    image: mysql
    ports:
      - "9903:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1
    restart: always
    networks:
      - jobs

  usersdb:
    container_name: usersdb
    image: mysql
    ports:
      - "9902:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1
    restart: always
    networks:
      - users

  chatdb:
    container_name: chatdb
    image: mysql
    ports:
      - "9909:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1
    restart: always
    networks:
      - chat

networks:
  alumni:
    driver: bridge
  events:
    driver: bridge
  jobs:
    driver: bridge
  users:
    driver: bridge
  chat:
    driver: bridge
