version: "3.8"
services:
  discovery:
    container_name: discovery
#    image: servicediscovery
    build:
      context: ./service-discovery
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always
    networks:
      - alumni
    environment:
      - PORT=8000
      - EUREKA_URI=http://discovery:8000/eureka

  config:
    container_name: config
    #image: configserver
    build:
      context: ./config-server
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    restart: always
    depends_on:
      - discovery
    networks:
      - alumni
    environment:
      - PORT=8001
      - EUREKA_URI=http://discovery:8000/eureka
      - EVENT_PORT=8801
      - EVENT_DB_URL=eventsdb:3306
      - EVENT_DB_NAME=eventsDb
      - EVENT_DB_USER=root
      - EVENT_DB_PASSWORD=1

  apigateway:
    container_name: apigateway
#    image: apigateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    restart: always
    depends_on:
      - discovery
      - config
    networks:
      - alumni
    environment:
      - PORT=8002
      - EUREKA_URI=http://discovery:8000/eureka

  eventservice:
    container_name: eventservice
#    image: eventservice
    build:
      context: ./EventService
      dockerfile: Dockerfile
    ports:
      - "8801:8801"
    restart: always
    depends_on:
      - discovery
      - config
      - apigateway
      - eventsdb
      - user-service
    networks:
      - alumni
      - events
    environment:
      - PORT=8801
      - EUREKA_URI=http://discovery:8000/eureka
      - CONFIG_URI=http://config:8001
      - EVENT_DB_URL=eventsdb:3306
      - EVENT_DB_NAME=eventsdb
      - EVENT_DB_USER=root
      - EVENT_DB_PASSWORD=1

  user-service:
    container_name: user-service
#    image: user-service
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    restart: on-failure
    depends_on:
      - discovery
      - config
      - apigateway
      - mysqldb-user
    networks:
      - alumni
      - users
    environment:
      - PORT=8181
      - EUREKA_URI=http://discovery:8000/eureka
      - CONFIG_URI=http://config:8001
      - USER_DB_URL=users_db:3306
      - USER_DB_NAME=users_db
      - USER_DB_USER=student
      - USER_DB_PASSWORD=cluster@1

  eventsdb:
    container_name: eventsdb
    image: mysql
    ports:
      - "9901:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1
    restart: always
    networks:
      - events

  mysqldb-user:
    container_name: mysqldb
    image: mysql
    ports:
      - "9906:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=cluster@1
    restart: always
    networks:
      - users

networks:
  alumni:
    driver: bridge
  events:
    driver: bridge
  users:
    driver: bridge
