scrape_configs:
  - job_name: 'ChatMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'chatservice:8809' ]
        labels:
          application: 'ChatService'